### ISSUE TITLE
wifi ESSID with spaces not correctly managed

### ISSUE THREAD

**Issue by ulipo** [dchristl/esp32_nat_router_extended#78] opened 2023-08-20 19:13 UTC
If the uplink wifi ESSID contains spaces, only the first word is kept in memory and if you push "Apply", the wrong ESSID is saved.

**Comment by dchristl** [comment] 2023-08-21 10:53
Hello @ulipo 

I've tried with both SSIDs and it works like expected:

![Screenshot_20230821-124800_Fennec](https://github.com/dchristl/esp32_nat_router_extended/assets/2836933/5088ffaa-9b12-420f-a9cf-e9ecc6104368)

I can edit and connect to uplink without any issues. How do you mange to input the data? Do you have the latest version installed? 

Kind regards,
Danny

**Comment by ulipo** [comment] 2023-08-21 11:30
I'm using version 6.3.0, my ESSID is "Installazione App..", I can enter it
normally and it works, but when I go back to the interface it shows only
"Installazione" and if I hit Apply for any reason, it changes to that ESSID.


Il lun 21 ago 2023, 12:53 dchristl ***@***.***> ha scritto:

**Comment by ulipo** [comment] 2023-08-21 14:52
I do exactly as you stated.
By "going back" to the interface I mean reconnecting at a later time to the
ESP32NAT web interface to check for updates and so on...

Il lun 21 ago 2023, 14:21 dchristl ***@***.***> ha scritto:

**Comment by dchristl** [comment] 2023-08-22 11:41
Does the connection work in general? Can you try another browser or which one do you use? I can't fix anything, if I can't reproduce the problem.

**Comment by ulipo** [comment] 2023-08-23 06:41
The connection works like a charm!
I tried with both Firefox and Chrome on two different Linux machines
(Debian and Ubuntu) and Firefox on Android, same results.
The only thing that's common to all this systems is the italian locale, I
tried to fake a different locale on Firefox/Linux with an extension, but
didn't change a thing.


Il mar 22 ago 2023, 13:42 dchristl ***@***.***> ha scritto:

**Comment by dchristl** [comment] 2023-08-23 15:50
So, everyting is saved correctly and it is only a view problem. The locale shouldn't be a problem. You can also try _wget_ if you are on Linux. I've also used Firefox, Chrome on Ubuntu and Fennec (Firefox-clone) on Android and everything seems to work fine.
Do you have another chip to try?  Can you open a terminal when visiting the site? Is there anything to see here?

**Comment by ulipo** [comment] 2023-08-24 12:46
Unfortunaltely I have no other chip at the moment.
I connected the board to my PC and [dumped the serial output](https://github.com/dchristl/esp32_nat_router_extended/files/12429605/terminal.txt), in sequence that's what I did:
- booted the board
- opened configuration page
- applied new parameters (with the correct SSID)
- waited for board rebooting


- reloaded config page

**Comment by dchristl** [comment] 2023-08-24 16:57
I can't see anything suspicious here. The only thing is, that you use a dev version. Could you update to the latest release version instead?

**Comment by ulipo** [comment] 2023-08-24 18:18
That's quite strange, I flashed manually 6.0.0 an then used OTA to update, it should have been the release version...
When I'll find some spare time, I'll try to completely erase the device and flash anew.

**Comment by dchristl** [comment] 2023-08-26 07:34
I apologize for the confusion. You have/had the correct version. There seems to be an error in reading the version number in the console. Nevertheless, my hands are tied here. I believe it might be an issue with the chip, but I'm not entirely sure. Since I can't replicate this, it's unfortunately unsolvable for me.

Two more options come to mind. Was there a past version where it worked? If so, which one? In that case, I could potentially check the repository to see if anything has changed at this part. Alternatively, you'd need to provide me with your inputs exactly, including the password, etc. It could be the combination of everything that is causing this issue.

**Comment by ulipo** [comment] 2023-08-26 17:01
I got myself a new esp32 board (not perfectly suitable as it only has an integrated antenna) and tried to install some versions.
Well, it seems that the problem started with v5.0.0, with v4.0.0 it works ok:
![immagine](https://github.com/dchristl/esp32_nat_router_extended/assets/32038266/ef92038d-e034-4cbc-b57c-4423ad6b8c72)

Here is the terminal dump:
[terminal.txt](https://github.com/dchristl/esp32_nat_router_extended/files/12446125/terminal.txt)

**Comment by dchristl** [comment] 2023-08-27 06:28
I think I've found the issue. The problem is the HTML file minification. The delivered HTML is heavily compressed to save space and reduce the amount of data transferred. This minifier removes duplicate double quotes in the HTML, which is why everything after the space is still in the HTML but not displayed anymore. When I'm developing, this feature is not active, which is why it worked for me. The latest version should solve your problem. You are able to update tis with OTA. Thank you for reporting the issue.

Kind regards,
Danny

**Comment by ulipo** [comment] 2023-08-27 07:22
Thanks Danny, I can confirm v6.3.1 it's working as intended.


Il dom 27 ago 2023, 08:29 dchristl ***@***.***> ha scritto:

**Comment by dchristl** [comment] 2023-08-27 08:40
Great, I will close this issue now.

**Closed by dchristl** 2023-08-27 08:40 UTC
